[package]
name = "rustwgpu"
version = "0.1.0"
authors = ["Vijfhoek <me@vijf.life>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
bytemuck = { version = "1.5.1", features = ["derive"] }
cgmath = "0.18.0"
env_logger = "0.8.3"
futures = "0.3.15"
image = "0.23.14"
log = "0.4.14"
wgpu = "0.8.1"
winit = { version = "0.25.0", default_features = false, features = ["x11"] }
